### ISSUE TITLE
2.2

### ISSUE THREAD

**Issue by Mattabase** [s0cks/RemoteIO#10]
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/03/crash-2015-03-14_21.01.47-client.txt

**Comment by s0cks** [comment]
Totally is a thaumcraft bug XD, although it could be incompatibility between the two mods I'll look into it

**Comment by Mattabase** [comment]
I see that,however it happens when installing the latest update of RIO =P

**Comment by s0cks** [comment]
Yeah I'll have to look into it then

**Comment by wasweb** [comment]
It's time to update all API! Not just Thaumcraft. (or remove them from the mod)

**Comment by s0cks** [comment]
Fixed
